### ISSUE TITLE
Add test for reloading the module with external iteration state via Cartridge hotreload

### ISSUE THREAD

**Issue by akudiyar** [tarantool/expirationd#54]
Use case:

A user creates an expiration task, for which the expiration check callback or the iteration function saves some state into the globals or `cartridge.vars` (e.g. iterator state or the last tuple value, etc). In case of reloading the module in a Cartridge role, the user must have the ability to preserve the state for continuing the iteration with it after the reload.

AC:

New integration test added for the above scenario and is passing in the CI

**Comment by vrogach2020** [comment]
After some discussions I think we should split this issue to support some cartridge-aware features:

 - Create catridge role for expirationd. This provides a common way to 
   use the module with cartridge and support standard role lifecycle (init, apply config, stop etc).

 - Configure tasks from YAML config

 - Support hot-reload of cartridge role

 - Save task state to continue iteration of large spaces

**Comment by Totktonada** [comment]
Regarding storing the state of the iterator. I had a question. We can do the following:

* Always start from beginning.
* Save a state in runtime.
* Persist the state in the database.

The second option is proposed, but it is not clear how this choice was made.

Now I got it: we can't just store a current key anymore, because there is ability to pass a custom iterator to expirationd. Okay so.
