### ISSUE TITLE
expirationd.lua:394: attempt to index a nil value

### ISSUE THREAD

**Issue by olegrok** [tarantool/expirationd#68]
Seems if we try to run a task for non-existent space_id we get such non-informative error

**Comment by Totktonada** [comment]
I would add here: there are cases, when we want to start expirationd disregarding whether the space (and the primary/requested index) is exists or not (and let expirationd to wait until the space/the index will appear). Otherwise it may be non-trivial to use expirationd together with https://github.com/tarantool/migrations.

Who are interested: @WeCodingNow, @ochaton, @no1seman.
